version: "3.9"

services:
  alma-db:
    image: postgres:15
    container_name: alma-db
    environment:
      POSTGRES_DB: alma-db
      POSTGRES_USER: alma-user
      POSTGRES_PASSWORD: alma-password
    ports:
      - "5432:5432"
    volumes:
      - alma-data:/var/lib/postgresql/data
      - ./backend/src/main/sql/01_quiz_schema.sql:/docker-entrypoint-initdb.d/01_quiz_schema.sql
      - ./backend/src/main/sql/02_quiz_data.sql:/docker-entrypoint-initdb.d/02_quiz_data.sql

  alma-ollama-init:
    image: docker.io/ollama/ollama:latest
    container_name: alma-ollama-init
    entrypoint: ["/bin/sh", "/ollama-init.sh"]
    volumes:
      - ollama-data:/root/.ollama
      - ./ollama-init.sh:/ollama-init.sh

  ollama:
    image: docker.io/ollama/ollama:latest
    container_name: alma-ollama
    restart: unless-stopped
    depends_on:
      alma-ollama-init:
        condition: service_completed_successfully
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    ports:
      - "11434:11434"
    environment:
      CUDA_VISIBLE_DEVICES: 0
      OLLAMA_KEEP_ALIVE: -1
      OLLAMA_FLASH_ATTENTION: 1
      OLLAMA_CONTEXT_LENGTH: 8192
      OLLAMA_KV_CACHE_TYPE: q4_0
      OLLAMA_DEBUG: 1
    volumes:
      - ollama-data:/root/.ollama
    healthcheck:
      test: ["CMD", "ollama", "--version"]
      interval: 1h
      timeout: 5s
      retries: 1
      start_period: 10s

volumes:
  alma-data:
  ollama-data: