services:
  alma-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: alma-backend
    restart: unless-stopped
    ports:
      - "8082:8082"
    depends_on:
      alma-db:
        condition: service_healthy
      ollama:
        condition: service_healthy

  alma-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: alma-frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - alma-backend

  alma-db:
    image: postgres:15
    container_name: alma-db
    environment:
      POSTGRES_DB: alma-db
      POSTGRES_USER: alma-user
      POSTGRES_PASSWORD: alma-password
    ports:
      - "5432:5432"
    volumes:
      - alma-data:/var/lib/postgresql/data
      - ./backend/src/main/sql/01_quiz_schema.sql:/docker-entrypoint-initdb.d/01_quiz_schema.sql
      - ./backend/src/main/sql/02_quiz_data.sql:/docker-entrypoint-initdb.d/02_quiz_data.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "alma-user", "-d", "alma-db"]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    image: docker.io/ollama/ollama:latest
    container_name: alma-ollama
    restart: unless-stopped
    entrypoint: ["/usr/bin/bash", "/ollama-init.sh"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    ports:
      - "11434:11434"
    environment:
      PRELOAD_MODEL_NAME: hf.co/unsloth/gemma-3n-E4B-it-GGUF:Q4_K_XL
      CUDA_VISIBLE_DEVICES: 0
      OLLAMA_MODELS: /root/.ollama/models
      OLLAMA_KEEP_ALIVE: -1
      OLLAMA_FLASH_ATTENTION: 1
      OLLAMA_CONTEXT_LENGTH: 8192
      OLLAMA_KV_CACHE_TYPE: q4_0
      OLLAMA_DEBUG: 1
    volumes:
      - ollama-data:/root/.ollama
      - ./ollama-init.sh:/ollama-init.sh
    healthcheck:
      test: ["CMD", "ollama", "--version"]
      interval: 1h
      timeout: 5s
      retries: 1
      start_period: 10s

volumes:
  alma-data:
  ollama-data: