server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/alma-db
    username: alma-user
    password: alma-password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      pool-name: quiz-hikari-pool
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


llm:
  prompts:
    default: "You are a helpful assistant. Answer the following question: {question}"
    quiz: "You are a quiz assistant. Answer the following question: {question}"
    chat: "You are a chat assistant. Respond to the user's message: {message}"
  provider: ollama      # ollama | openai | localai | bedrock | ...
  model: hf.co/unsloth/gemma-3n-E4B-it-GGUF:Q4_K_XL         # el modelo a usar
  api:
    base-url: http://localhost:11434
    key: ""             # solo necesario si el proveedor lo requiere

  jackson:
    serialization:
      indent_output: true
    default-property-inclusion: non_null

logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.shark.alma: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
